version: "2"
services:
  force:
    build:
      dockerfile: Dockerfile.test
    command: yarn test
    extends:
      file: build.yml
      service: force
    environment:
      - CI=true
      - CIRCLE_NODE_INDEX
    env_file: ../.env.test
